# Copyright 2021-2022 by Vegard IT GmbH, Germany, https://vegardit.com
# SPDX-License-Identifier: EPL-2.0
#
# Author: Sebastian Thomschke, Vegard IT GmbH
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Keep Workflows Alive

on:
  schedule:
    - cron:  '0 0 1 * *' # monthly
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/


jobs:
  keep-workflows-alive:
    runs-on: ubuntu-latest
  
    steps:
    - name: Keep Workflows alive
      shell: bash
      run: |
        set -eux

        workflow_api_url=https://x-access-token:${{ secrets.GH_TOKEN }}@api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows

        for workflow in $(curl -sSf -H "Accept: application/vnd.github.v3+json" $workflow_api_url | jq '.workflows[]| (.id|tostring) + "_" + .name' -r); do
           workflow_id=$(echo "$workflow" | cut -d: -f2-)
           workflow_name=$(echo "$workflow" | cut -d: -f1)
           echo "Enabling [$workflow_name] with id [$workflow_id]..."
           curl -I -X PUT -H "Accept: application/vnd.github.v3+json" $workflow_api_url/$workflow_id/enable
        done
