# Copyright 2021-2022 by Vegard IT GmbH, Germany, https://vegardit.com
# SPDX-License-Identifier: EPL-2.0
#
# Author: Sebastian Thomschke, Vegard IT GmbH
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Mirror Repos

on:
  schedule:
  - cron:  '5 8,12,16,20 * * *' # at 8:05,12:05,16:05,20:05 UTC
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/


jobs:
  mirror-repos:
    runs-on: ubuntu-latest
    concurrency: mirror-repos-${{ matrix.target }} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idconcurrency
    strategy:
      fail-fast: false
      matrix:
        include:
        # now at https://github.com/eclipse-platform/eclipse.platform
        #- { target: "org.eclipse.core.resources", source: "https://git.eclipse.org/r/platform/eclipse.platform.resources.git" }

        # now at https://github.com/eclipse-platform/eclipse.platform.XYZ
        #- { target: "org.eclipse.debug",          source: "https://git.eclipse.org/r/platform/eclipse.platform.debug.git" }
        #- { target: "org.eclipse.ui",             source: "https://git.eclipse.org/r/platform/eclipse.platform.ui.git" }

        # now at https://github.com/eclipse-equinox/equinox
        #- { target: "org.eclipse.equinox",        source: "https://git.eclipse.org/r/equinox/rt.equinox.bundles.git" }

        # now at https://github.com/eclipse-jdt/eclipse.jdt.XYZ
        #- { target: "org.eclipse.jdt.core",       source: "https://git.eclipse.org/r/jdt/eclipse.jdt.core.git" }
        #- { target: "org.eclipse.jdt.debug",      source: "https://git.eclipse.org/r/jdt/eclipse.jdt.debug.git" }
        #- { target: "org.eclipse.jdt.ui",         source: "https://git.eclipse.org/r/jdt/eclipse.jdt.ui.git" }

        # now at https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs
        #- { target: "org.eclipse.mylyn.docs",     source: "https://git.eclipse.org/r/mylyn/org.eclipse.mylyn.docs.git", ignore_error: true }

        # moved to https://github.com/merks/emf-xsd
        #- { target: "org.eclipse.xsd",            source: "https://git.eclipse.org/r/xsd/org.eclipse.xsd.git" }

        - { target: "org.eclipse.egit",           source: "https://git.eclipse.org/r/egit/egit.git" }
        - { target: "org.eclipse.jgit",           source: "https://git.eclipse.org/r/jgit/jgit.git" }

        - { target: "org.eclipse.xwt",            source: "https://git.eclipse.org/r/xwt/org.eclipse.xwt.git" }

    steps:
    - name: Mirroring ${{ matrix.target }}
      shell: bash
      continue-on-error: ${{ matrix.ignore_error || false }}
      run: |
        set -eux
        date

        git clone --mirror "${{ matrix.source }}" source_repo 
        cd source_repo
        git remote set-url --push origin "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/eclipse-mirrors/${{ matrix.target }}"
        git config --add remote.origin.fetch '^refs/changes/*' # ignore PRs
        git config --add remote.origin.fetch '^refs/pull/*'    # ignore Gerrit changesets 

        { echo "::group::git fetch"; } 2> /dev/null
           git fetch --prune --prune-tags --verbose origin
        { echo "::endgroup::"; } 2> /dev/null

        # purge any potential PRs/Gerrit changesets from initial import
        git for-each-ref --format 'delete %(refname)' refs/pull/* refs/changes/* | git update-ref --stdin

        # git push --mirror 
        # |-> results in remote: Internal Server Error, see https://github.com/isaacs/github/issues/1253

        # workaround:
        git config --unset remote.origin.mirror # https://stackoverflow.com/a/49339040/5116073
        git for-each-ref --format="%(refname)" --sort=authordate refs/heads | xargs git push --force --verbose origin # https://stackoverflow.com/a/65416524/5116073
